//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dispensery
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllHerb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AllHerb()
        {
            this.HerbStocks = new HashSet<HerbStock>();
            this.PatentFormulas = new HashSet<PatentFormula>();
            this.PrescriptionMainTemps = new HashSet<PrescriptionMainTemp>();
            this.PrescriptionMains = new HashSet<PrescriptionMain>();
        }
    
        public string RefNum { get; set; }
        public string HerbNameChinese { get; set; }
        public string HerbName { get; set; }
        public string PharmaName { get; set; }
        public string EnglishName { get; set; }
        public string Temperature { get; set; }
        public string Description { get; set; }
        public string Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HerbStock> HerbStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatentFormula> PatentFormulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionMainTemp> PrescriptionMainTemps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionMain> PrescriptionMains { get; set; }
    }
}
