//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dispensery
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatentFormulaStock
    {
        public int PatentFormulaStockId { get; set; }
        public string FormulaRefNum { get; set; }
        public string FormulaName { get; set; }
        public Nullable<int> BottleQuantity { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Status { get; set; }
    }
}
