//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dispensery
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatentFormula
    {
        public int PatentFormulaID { get; set; }
        public string FormulaName { get; set; }
        public string HerbRefNum { get; set; }
        public Nullable<decimal> DosageProcentage { get; set; }
        public Nullable<decimal> DosageGrams { get; set; }
    
        public virtual AllHerb AllHerb { get; set; }
    }
}
