//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dispensery
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatentFormulaSaleHistory
    {
        public int PFSaleId { get; set; }
        public Nullable<int> PractitionerID { get; set; }
        public string PFbatchNum { get; set; }
        public Nullable<int> BottleQuantity { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
    
        public virtual Practitioner Practitioner { get; set; }
    }
}
