//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dispensery
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionTemp
    {
        public int Id { get; set; }
        public string RefNum { get; set; }
        public string HerbName { get; set; }
        public decimal Quantity { get; set; }
        public decimal PhenixPrice { get; set; }
        public decimal BalancePrice { get; set; }
    }
}
