//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dispensery
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionCost
    {
        public int PrescriptionID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string FormulaRefNum { get; set; }
        public Nullable<decimal> FormulaTotalCost { get; set; }
        public string MethodOfAdminist { get; set; }
        public Nullable<decimal> MethodOfAdministCOST { get; set; }
        public Nullable<decimal> DispensingFee { get; set; }
        public string Postage { get; set; }
        public Nullable<decimal> PostageFee { get; set; }
        public string PrescriptionStatus { get; set; }
        public string DiscountReason { get; set; }
        public Nullable<decimal> Discount { get; set; }
    }
}
